name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Formatting
        run: yarn format

      - name: Linting
        run: yarn lint

      - name: Build
        run: yarn build
